# Generated by Django 5.2 on 2025-04-11 17:36

import django.db.models.deletion
import pdf_parser.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=pdf_parser.models.upload_to_pdfs)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('has_anomalies', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(blank=True, null=True)),
                ('modification_date', models.DateTimeField(blank=True, null=True)),
                ('num_pages', models.IntegerField(default=0)),
                ('num_images', models.IntegerField(default=0)),
                ('suspicious_areas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_date', models.DateTimeField(auto_now_add=True)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('location_data', models.JSONField(blank=True, null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='pdf_parser.pdfdocument')),
            ],
        ),
        migrations.CreateModel(
            name='PDFImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('page_number', models.IntegerField()),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('size_bytes', models.IntegerField(default=0)),
                ('image_type', models.CharField(default='unknown', max_length=20)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('entropy_score', models.FloatField(blank=True, null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pdf_parser.pdfdocument')),
            ],
        ),
    ]
