# Generated by Django 5.2.1 on 2025-06-02 12:57

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StegoOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('hide', 'Hide Image in PDF'), ('extract', 'Extract Image from PDF')], max_length=10)),
                ('method', models.CharField(choices=[('stream', 'Object Stream Manipulation'), ('metadata', 'Metadata Embedding'), ('whitespace', 'White Space and Comment Exploitation'), ('components', 'Document Components Manipulation'), ('javascript', 'JavaScript Integration'), ('random', 'Random Selection')], max_length=20)),
                ('actual_method', models.CharField(blank=True, max_length=20, null=True)),
                ('input_pdf', models.FileField(blank=True, null=True, upload_to='stego/input_pdfs/')),
                ('input_png', models.ImageField(blank=True, null=True, upload_to='stego/input_pngs/')),
                ('output_pdf', models.FileField(blank=True, null=True, upload_to='stego/output_pdfs/')),
                ('stego_pdf', models.FileField(blank=True, null=True, upload_to='stego/extracted/stego_pdfs/')),
                ('extracted_png', models.ImageField(blank=True, null=True, upload_to='stego/extracted/extracted_pngs/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
