# Generated by Django 5.2 on 2025-04-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_stego', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stegooperation',
            name='extracted_png',
            field=models.ImageField(blank=True, null=True, upload_to='stego/extracted/extracted_pngs/'),
        ),
        migrations.AlterField(
            model_name='stegooperation',
            name='input_pdf',
            field=models.FileField(blank=True, null=True, upload_to='stego/input_pdfs/'),
        ),
        migrations.AlterField(
            model_name='stegooperation',
            name='input_png',
            field=models.ImageField(blank=True, null=True, upload_to='stego/input_pngs/'),
        ),
        migrations.AlterField(
            model_name='stegooperation',
            name='output_pdf',
            field=models.FileField(blank=True, null=True, upload_to='stego/output_pdfs/'),
        ),
        migrations.AlterField(
            model_name='stegooperation',
            name='stego_pdf',
            field=models.FileField(blank=True, null=True, upload_to='stego/extracted/stego_pdfs/'),
        ),
    ]
