# Generated by Django 5.2.1 on 2025-05-10 14:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('clean_count', models.IntegerField(default=0)),
                ('stego_count', models.IntegerField(default=0)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clean_pdf_count', models.IntegerField(default=0)),
                ('stego_pdf_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model_type', models.CharField(choices=[('cnn', 'Convolutional Neural Network'), ('xgboost', 'XGBoost'), ('lstm', 'LSTM'), ('ensemble', 'Ensemble Model')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('accuracy', models.FloatField(default=0.0)),
                ('file_path', models.CharField(max_length=512)),
                ('is_active', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detector_app.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='PDFScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.CharField(choices=[('clean', 'Clean'), ('stego', 'Steganography Detected'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('model_used', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detector_app.trainedmodel')),
            ],
        ),
    ]
