# Generated by Django 5.2.1 on 2025-06-02 06:33

import detector_app.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=detector_app.models.upload_to_pdfs)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_malicious', models.BooleanField(blank=True, null=True)),
                ('ensemble_probability', models.FloatField(blank=True, null=True)),
                ('confidence_percentage', models.FloatField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, choices=[('MINIMAL', 'Minimal'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('attention_probability', models.FloatField(blank=True, null=True)),
                ('deep_ff_probability', models.FloatField(blank=True, null=True)),
                ('wide_deep_probability', models.FloatField(blank=True, null=True)),
                ('pdf_pages', models.IntegerField(blank=True, null=True)),
                ('metadata_size', models.IntegerField(blank=True, null=True)),
                ('suspicious_count', models.IntegerField(blank=True, null=True)),
                ('javascript_elements', models.IntegerField(blank=True, null=True)),
                ('auto_actions', models.IntegerField(blank=True, null=True)),
                ('embedded_files', models.IntegerField(blank=True, null=True)),
                ('extracted_features', models.JSONField(blank=True, null=True)),
                ('individual_predictions', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Scan Result',
                'verbose_name_plural': 'PDF Scan Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='BulkScan',
        ),
        migrations.RemoveField(
            model_name='trainedmodel',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='pdfscan',
            name='model_used',
        ),
        migrations.DeleteModel(
            name='Dataset',
        ),
        migrations.DeleteModel(
            name='PDFScan',
        ),
        migrations.DeleteModel(
            name='TrainedModel',
        ),
    ]
