# Generated by Django 5.2.1 on 2025-06-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_datasetinfo_mlmodel_predictionlog_trainingsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
